<a href="https://colab.research.google.com/github/Alena-Andriyash/ML_Pylieva_tasks/blob/main/HW_2_2_%D0%9C%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%BD%D0%B5_%D1%84%D0%BE%D1%80%D0%BC%D1%83%D0%BB%D1%8E%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F_%D0%BB%D0%BE%D0%B3%D1%96%D1%81%D1%82%D0%B8%D1%87%D0%BD%D0%BE%D1%97_%D1%80%D0%B5%D0%B3%D1%80%D0%B5%D1%81%D1%96%D1%97_%D0%90%D0%BD%D0%B4%D1%80%D1%96%D1%8F%D1%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

В цьому домашньому завданні ми реалізуємо логістичну регресію на `numpy`.
Ці завдання допоможуть вам ґрунтовно засвоїти основні концепції логістичної регресії та реалізувати їх на практиці 🔥

#### Завдання 1: Реалізація функції сигмоїди
1. З використанням `numpy` напишіть функцію `sigmoid(z)` для обчислення значення сигмоїди згідно з формулою:
   $$
   \sigma(z) = \frac{1}{1 + e^{-z}}
   $$
2. Використовуючи цю функцію, обчисліть значення сигмоїди для наступних даних: $ z = [-2, -1, 0, 1, 2] $. Виведіть результат обчислень.


In [1]:
import numpy as np

In [2]:
z = np.array([-2, -1, 0, 1, 2])

In [43]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [9]:
sigmoid_values = sigmoid(z)

In [10]:
print("Значення сигмоїди для z = [-2, -1, 0, 1, 2]:", sigmoid_values)

Значення сигмоїди для z = [-2, -1, 0, 1, 2]: [0.11920292 0.26894142 0.5        0.73105858 0.88079708]




#### Завдання 2: Реалізація функції гіпотези для логістичної регресії
1. Напишіть функцію `hypothesis(theta, X)`, яка обчислює гіпотезу для логістичної регресії, використовуючи функцію сигмоїди. Формула гіпотези:
   $$
   h_\theta(x) = \sigma(\theta^T x) = \frac{1}{1 + e^{-\theta^T x}}
   $$
2. Використайте функцію `hypothesis` для обчислення значень гіпотези для наступних даних:
   
   $\theta = [0.5, -0.5]$
   
   $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  Виведіть результат обчислень.


In [12]:
def hypothesis(theta, X):
    z = np.dot(X, theta)
    return sigmoid(z)

In [13]:
theta = np.array([0.5, -0.5])
X = np.array([[1, 2],
              [1, -1],
              [0, 1],
              [1, 1]])

In [14]:
h = hypothesis(theta, X)

In [15]:
h

array([0.37754067, 0.73105858, 0.37754067, 0.5       ])

#### Завдання 3: Реалізація функції для підрахунку градієнтів фукнції втрат
1. Напишіть функцію `compute_gradient(theta, X, y)`, яка обчислює градієнти функції втрат для логістичної регресії. Формула для обчислення градієнта:
   $$
   \frac{\partial L(\theta)}{\partial \theta_j} = \frac{1}{m} \sum_{i=1}^{m} \left[ (h_\theta(x^{(i)}) - y^{(i)}) x_j^{(i)} \right]
   $$
2. Використайте функцію `compute_gradient` для обчислення градієнтів для наступних даних:

  $\theta = [0.5, -0.5]$

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Виведіть результат обчислень.

In [17]:
X,theta

(array([[ 1,  2],
        [ 1, -1],
        [ 0,  1],
        [ 1,  1]]),
 array([ 0.5, -0.5]))

In [18]:
y =np.array([1,0,1,0])

In [44]:
def compute_gradient(theta, X, y):
    m = len(y)
    h = hypothesis(theta, X)
    gradient = (1 / m) * np.dot(X.T, (h - y))
    return gradient


In [19]:
compute_gradient(theta, X, y)

array([ 0.15214981, -0.52460914])


#### Завдання 4: Реалізація повного батч градієнтного спуску

**Задача:**
1. Напишіть функцію `full_batch_gradient_descent(X, y, lr=0.1, epochs=100)`, яка реалізує алгоритм Full градієнтного спуску для логістичної регресії. Використовуйте такі формули:
   - Гіпотеза: $ h_\theta(x) = \sigma(\theta^T x) $
   - Оновлення параметрів: $ \theta_j := \theta_j - \alpha \frac{\partial L(\theta)}{\partial \theta_j} $
2. Використайте функцію `full_batch_gradient_descent` для обчислення параметрів моделі на наступних даних:

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Увага! Матриця $X$ вже має стовпець одиниць і передбачається, що це. - стовпець для intercept - параметра зсуву.

  Виведіть результат обчислень.


In [45]:
X = np.array([[1, 2],
              [1, -1],
              [1, 0],
              [1, 1]])
y = np.array([1, 0, 1, 0])

In [46]:
theta = np.zeros(X.shape[1])

In [41]:
def full_batch_gradient_descent(theta, X, y, lr=0.1, epochs=100):
    for epoch in range(epochs):
        gradient = compute_gradient(theta, X, y)
        theta -= lr * gradient
    return theta

In [42]:
final_theta = full_batch_gradient_descent(theta, X, y, lr=0.1, epochs=100)
print("Фінальні параметри theta:", final_theta)

Фінальні параметри theta: [-0.2893693   0.77655125]


#### Завдання 5. Обчислення точності моделі

1. Напишіть функцію `predict_proba(theta, X)`, яка використовує знайдені параметри $\theta$ для обчислення ймовірностей належності поточного прикладу з даних до класу $y=1$ на основі значень $\sigma(\theta^T x)$.

2. Напишіть функцію `predict(theta, X, threshold=0.5)`, яка обчислює клас з передбаченої імовірності належності екземпляра до класу 1 з порогом 0.5. Тобто якщо ймовірність менше 0.5, то передбачаємо клас 0, інакше клас 1.

3. Напишіть функцію `accuracy(y_true, y_pred)`, яка обчислює точність моделі, визначивши частку правильно передбачених класів.

  Формула метрики Accuracy:
  $$
  \text{Accuracy} = \frac{\sum_{i=1}^{m} I(\hat{{y}^{(i)}} = y^{(i)})}{m}
  $$

  де $\hat{{y}^{(i)}}$ - передбачене значення класу, $I$ - індикаторна функція (яка дорівнює 1, якщо умова виконується, і 0 - якщо ні), $m$ - кількість прикладів.

4. Обчисліть з використанням даних в завданні 4 $X$, $y$ та обчислених коефіцієнтах $\theta$ та виведіть на екран:
  - передбачені моделлю імовірності належності кожного з екземплярів в матриці `X` до класу 1
  - класи кожного екземпляра з матриці `X`
  - точність моделі.

In [47]:
def predict_proba(theta, X):
      return hypothesis(theta, X)

In [48]:
probabilities = predict_proba(final_theta, X)
probabilities

array([0.77966809, 0.25617965, 0.42815828, 0.61944235])

In [55]:
def predict(theta, X, threshold=0.5):
    probabilities = predict_proba(theta, X)
    return (probabilities >= threshold).astype(int)

In [56]:
predicted_classes = predict(final_theta, X)
predicted_classes

array([1, 0, 0, 1])

In [57]:
def accuracy(y_true, y_pred):
    m = len(y_true)
    correct_predictions = np.sum(y_true == y_pred)
    return correct_predictions / m

In [59]:
accuracy_score = accuracy(y, predicted_classes)
accuracy_score

0.5

In [60]:
X = np.array([[1, 2],
              [1, -1],
              [1, 0],
              [1, 1]])
y = np.array([1, 0, 1, 0])

In [61]:
predicted_probabilities = predict_proba(final_theta, X)

In [62]:
predicted_classes = predict(final_theta, X)

In [63]:
accuracy_score = accuracy(y, predicted_classes)

In [64]:
print("Передбачені ймовірності належності кожного екземпляра до класу 1:")
print(predicted_probabilities)

print("\nПередбачені класи для кожного екземпляра:")
print(predicted_classes)

print("\nТочність моделі (Accuracy):")
print(accuracy_score)


Передбачені ймовірності належності кожного екземпляра до класу 1:
[0.77966809 0.25617965 0.42815828 0.61944235]

Передбачені класи для кожного екземпляра:
[1 0 0 1]

Точність моделі (Accuracy):
0.5
