<a href="https://colab.research.google.com/github/Alena-Andriyash/ML_Pylieva_tasks/blob/main/HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8)_Andriiash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import random

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [38]:
vector = np.random.rand(10)

In [40]:
vector

array([0.3667155 , 0.48502077, 0.22026366, 0.49528836, 0.69895206,
       0.692657  , 0.3004871 , 0.14959732, 0.98691003, 0.44585288])

In [4]:
matrix = np.array([
    [11, 20, 29],
    [14, 23, 32],
    [17, 26, 35]
])

matrix

array([[11, 20, 29],
       [14, 23, 32],
       [17, 26, 35]])


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [8]:
vector_plus_10 = np.round(vector + 10, 2)
vector_plus_10

array([10.13, 10.58, 10.12, 10.83, 10.43, 10.53, 10.66, 10.05, 10.19,
       10.39])

In [9]:
matrix_2 = matrix * 2

matrix_2

array([[22, 40, 58],
       [28, 46, 64],
       [34, 52, 70]])

In [10]:
vector_squared = vector**2
vector_squared

array([0.01595076, 0.33974724, 0.01417558, 0.68074211, 0.18470661,
       0.28558587, 0.44112644, 0.00247668, 0.03653619, 0.14834381])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [11]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [17]:
result_matrix = np.dot(B, A)

result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

Коли ми множимо матрицю
result_matrix
result_matrix розмірності
2×2 на вектор
C розмірності
2×1, отримуємо новий вектор розмірності
2×1

In [21]:
result_matrix_2 = np.dot(result_matrix, C)
result_matrix_2

array([[0.5202],
       [0.2846]])

Коли ми множимо матрицю
result_matrix розмірності
2×2 на матрицю
D розмірності
2×2, результуюча матриця буде також розмірності
2×2

In [23]:
result_with_D = np.dot(result_matrix, D)

result_with_D

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [26]:
result_matrix_t = result_matrix.T
result_matrix_t

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [31]:
print('result_matrix:')
print(result_matrix)
print('result_matrix_t:')
print(result_matrix_t)

result_matrix:
[[0.7281 0.5202]
 [0.2034 0.2846]]
result_matrix_t:
[[0.7281 0.2034]
 [0.5202 0.2846]]


In [41]:
vector_t = vector.T

In [42]:
print('vector:')
print(vector)
print('vector_t:')
print(vector_t)

vector:
[0.3667155  0.48502077 0.22026366 0.49528836 0.69895206 0.692657
 0.3004871  0.14959732 0.98691003 0.44585288]
vector_t:
[0.3667155  0.48502077 0.22026366 0.49528836 0.69895206 0.692657
 0.3004871  0.14959732 0.98691003 0.44585288]


In [43]:
vector.shape

(10,)

In [44]:
vector_t.shape

(10,)

Після транспонування вектора
vector
vector:

Початкова форма:
(10,)
Транспонована форма:
(10,)

In [45]:
column_vector = np.expand_dims(vector, axis=1)

In [46]:
column_vector

array([[0.3667155 ],
       [0.48502077],
       [0.22026366],
       [0.49528836],
       [0.69895206],
       [0.692657  ],
       [0.3004871 ],
       [0.14959732],
       [0.98691003],
       [0.44585288]])

In [47]:
vector

array([0.3667155 , 0.48502077, 0.22026366, 0.49528836, 0.69895206,
       0.692657  , 0.3004871 , 0.14959732, 0.98691003, 0.44585288])

In [48]:
vector.shape

(10,)

In [49]:
column_vector.shape

(10, 1)

Форма вектора змінюється з одномірного масиву (10,) на двовимірний стовпчик (10,1)

In [50]:
transposed_column_vector = column_vector.T

In [51]:
print("column_vector (original):")
print(column_vector)
print("Shape:", column_vector.shape)

print("\ntransposed_column_vector:")
print(transposed_column_vector)
print("Shape:", transposed_column_vector.shape)

column_vector (original):
[[0.3667155 ]
 [0.48502077]
 [0.22026366]
 [0.49528836]
 [0.69895206]
 [0.692657  ]
 [0.3004871 ]
 [0.14959732]
 [0.98691003]
 [0.44585288]]
Shape: (10, 1)

transposed_column_vector:
[[0.3667155  0.48502077 0.22026366 0.49528836 0.69895206 0.692657
  0.3004871  0.14959732 0.98691003 0.44585288]]
Shape: (1, 10)
